// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OfficeFileManagementSystem.Models;

#nullable disable

namespace OfficeFileManagementSystem.Migrations
{
    [DbContext(typeof(ApplicationDbSet))]
    [Migration("20230710163608_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OfficeFileManagementSystem.Models.Assignment", b =>
                {
                    b.Property<int>("Assignment_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Assignment_Id"));

                    b.Property<DateTime>("Date_Allowed")
                        .HasColumnType("Date")
                        .HasColumnName("Date_Allowed");

                    b.Property<int>("Employee_Id")
                        .HasColumnType("int");

                    b.Property<int>("Incoming_File_Id")
                        .HasColumnType("int");

                    b.HasKey("Assignment_Id");

                    b.ToTable("assignments");
                });

            modelBuilder.Entity("OfficeFileManagementSystem.Models.Employee", b =>
                {
                    b.Property<string>("Emp_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("Contact_Number")
                        .HasMaxLength(10)
                        .HasColumnType("int");

                    b.Property<string>("Employee_Designation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Employee_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Emp_Id");

                    b.ToTable("employees");
                });

            modelBuilder.Entity("OfficeFileManagementSystem.Models.Importance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Days_Allowed")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("importances");
                });

            modelBuilder.Entity("OfficeFileManagementSystem.Models.IncomingFile", b =>
                {
                    b.Property<int>("Incoming_File_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Incoming_File_Id"));

                    b.Property<DateTime>("Date_Allowed")
                        .HasColumnType("Date")
                        .HasColumnName("Date_Allowed");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Importance_ID")
                        .HasColumnType("int");

                    b.HasKey("Incoming_File_Id");

                    b.ToTable("incomingFiles");
                });

            modelBuilder.Entity("OfficeFileManagementSystem.Models.OutgoingFile", b =>
                {
                    b.Property<int>("Out_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Out_Id"));

                    b.Property<DateTime>("Date_Allowed")
                        .HasColumnType("Date")
                        .HasColumnName("Date_Allowed");

                    b.Property<int>("Emp_Id")
                        .HasColumnType("int");

                    b.Property<int>("Incoming_File_Id")
                        .HasColumnType("int");

                    b.HasKey("Out_Id");

                    b.ToTable("outgoingFiles");
                });
#pragma warning restore 612, 618
        }
    }
}
